//! Generated by LLM (Deepseek)

const std = @import("std");

/// 执行 CPUID 指令，返回 EAX、EBX、ECX、EDX 四个寄存器。
/// 仅支持 x86/x86_64 目标。
pub fn cpuid(eax: u32, ecx: u32) struct { eax: u32, ebx: u32, ecx: u32, edx: u32 } {
    var eax_out: u32 = undefined;
    var ebx_out: u32 = undefined;
    var ecx_out: u32 = undefined;
    var edx_out: u32 = undefined;
    asm volatile ("cpuid"
        : [_] "={eax}" (eax_out),
          [_] "={ebx}" (ebx_out),
          [_] "={ecx}" (ecx_out),
          [_] "={edx}" (edx_out),
        : [_] "{eax}" (eax),
          [_] "{ecx}" (ecx),
        : "memory");
    return .{
        .eax = eax_out,
        .ebx = ebx_out,
        .ecx = ecx_out,
        .edx = edx_out,
    };
}

// ----------------------------------------------------------------------
// Leaf 0 – 获取最大标准叶子和厂商字符串
// ----------------------------------------------------------------------
pub const Leaf0 = struct {
    max_leaf: u32,
    vendor_string: [12]u8,
};

/// 返回 Leaf 0 信息。
pub fn getLeaf0() Leaf0 {
    const r = cpuid(0, 0);
    var vendor: [12]u8 = undefined;
    @memcpy(vendor[0..4], @as(*const [4]u8, @ptrCast(&r.ebx)));
    @memcpy(vendor[4..8], @as(*const [4]u8, @ptrCast(&r.edx)));
    @memcpy(vendor[8..12], @as(*const [4]u8, @ptrCast(&r.ecx)));
    return .{ .max_leaf = r.eax, .vendor_string = vendor };
}

// ----------------------------------------------------------------------
// Leaf 1 – 处理器签名、品牌信息、特性标志
// ----------------------------------------------------------------------
/// Leaf 1 ECX 寄存器中的特性标志。
pub const Leaf1Ecx = packed struct(u32) {
    /// Streaming SIMD Extensions 3
    sse3: u1 = 0,
    /// PCLMULQDQ Instruction
    pclmulqdq: u1 = 0,
    /// 64-bit Debug Store Area
    dtes64: u1 = 0,
    /// MONITOR/MWAIT Instructions
    monitor: u1 = 0,
    /// CPL Qualified Debug Store
    ds_cpl: u1 = 0,
    /// Virtual Machine Extensions
    vmx: u1 = 0,
    /// Safer Mode Extensions
    smx: u1 = 0,
    /// Enhanced Intel SpeedStep Technology
    est: u1 = 0,
    /// Thermal Monitor 2
    tm2: u1 = 0,
    /// Supplemental Streaming SIMD Extensions 3
    ssse3: u1 = 0,
    /// L1 Context ID
    cnxt_id: u1 = 0,
    /// Silicon Debug Interface
    sdbg: u1 = 0,
    /// Fused Multiply-Add
    fma: u1 = 0,
    /// CMPXCHG16B Instruction
    cx16: u1 = 0,
    /// xTPR Update Control
    xtpr: u1 = 0,
    /// Perfmon and Debug Capability
    pdcm: u1 = 0,
    /// Reserved (bit 16)
    _reserved_16: u1 = 0,
    /// Process-Context Identifiers
    pcid: u1 = 0,
    /// Direct Cache Access
    dca: u1 = 0,
    /// SSE4.1 Instructions
    sse4_1: u1 = 0,
    /// SSE4.2 Instructions
    sse4_2: u1 = 0,
    /// x2APIC Support
    x2apic: u1 = 0,
    /// MOVBE Instruction
    movbe: u1 = 0,
    /// POPCNT Instruction
    popcnt: u1 = 0,
    /// TSC-Deadline Timer
    tsc_deadline: u1 = 0,
    /// AES Instructions
    aes: u1 = 0,
    /// XSAVE/XRSTOR Processor Extended States
    xsave: u1 = 0,
    /// OSXSAVE
    osxsave: u1 = 0,
    /// Advanced Vector Extensions
    avx: u1 = 0,
    /// 16-bit Floating-Point Conversion
    f16c: u1 = 0,
    /// RDRAND Instruction
    rdrand: u1 = 0,
    /// Reserved (bit 31)
    _reserved_31: u1 = 0,
};

/// Leaf 1 EDX 寄存器中的特性标志。
pub const Leaf1Edx = packed struct(u32) {
    /// Floating-Point Unit On-Chip
    fpu: u1 = 0,
    /// Virtual 8086 Mode Extensions
    vme: u1 = 0,
    /// Debugging Extensions
    de: u1 = 0,
    /// Page Size Extension
    pse: u1 = 0,
    /// Time Stamp Counter
    tsc: u1 = 0,
    /// Model-Specific Registers
    msr: u1 = 0,
    /// Physical Address Extension
    pae: u1 = 0,
    /// Machine Check Exception
    mce: u1 = 0,
    /// CMPXCHG8B Instruction
    cx8: u1 = 0,
    /// APIC On-Chip
    apic: u1 = 0,
    /// Reserved (bit 10)
    _reserved_10: u1 = 0,
    /// SYSENTER and SYSEXIT Instructions
    sep: u1 = 0,
    /// Memory Type Range Registers
    mtrr: u1 = 0,
    /// Page Global Enable
    pge: u1 = 0,
    /// Machine Check Architecture
    mca: u1 = 0,
    /// CMOV Instructions
    cmov: u1 = 0,
    /// Page Attribute Table
    pat: u1 = 0,
    /// 36-bit Page Size Extension
    pse36: u1 = 0,
    /// Processor Serial Number
    psn: u1 = 0,
    /// CLFLUSH Instruction
    clfsh: u1 = 0,
    /// Reserved (bit 20)
    _reserved_20: u1 = 0,
    /// Debug Store
    ds: u1 = 0,
    /// ACPI via MSR
    acpi: u1 = 0,
    /// MMX Technology
    mmx: u1 = 0,
    /// FXSAVE and FXRSTOR Instructions
    fxsr: u1 = 0,
    /// SSE Instructions
    sse: u1 = 0,
    /// SSE2 Instructions
    sse2: u1 = 0,
    /// Self Snoop
    ss: u1 = 0,
    /// Hyper-Threading Technology
    htt: u1 = 0,
    /// Thermal Monitor
    tm: u1 = 0,
    /// IA-64 Processor (reserved)
    ia64: u1 = 0,
    /// Pending Break Enable
    pbe: u1 = 0,
};

/// Leaf 1 完整信息。
pub const Leaf1 = struct {
    eax: u32, // 处理器签名（Family/Model/Stepping）
    ebx: u32, // 品牌索引等
    ecx: Leaf1Ecx,
    edx: Leaf1Edx,
};

/// 返回 Leaf 1 信息。
pub fn getLeaf1() Leaf1 {
    const r = cpuid(1, 0);
    return .{
        .eax = r.eax,
        .ebx = r.ebx,
        .ecx = @bitCast(r.ecx),
        .edx = @bitCast(r.edx),
    };
}

// ----------------------------------------------------------------------
// Leaf 7 – 扩展特性（需指定子叶，通常子叶 0）
// ----------------------------------------------------------------------
/// Leaf 7, Subleaf 0 EBX 中的特性标志。
pub const Leaf7Sub0Ebx = packed struct(u32) {
    /// FS/GS Base Access Instructions
    fsgsbase: u1 = 0,
    /// IA32_TSC_ADJUST MSR
    tsc_adjust: u1 = 0,
    /// Software Guard Extensions
    sgx: u1 = 0,
    /// Bit Manipulation Instruction Set 1
    bmi1: u1 = 0,
    /// Hardware Lock Elision
    hle: u1 = 0,
    /// Advanced Vector Extensions 2
    avx2: u1 = 0,
    /// FPU Data Pointer Updated on Exception Only
    fdp_excptn_only: u1 = 0,
    /// Supervisor Mode Execution Prevention
    smep: u1 = 0,
    /// Bit Manipulation Instruction Set 2
    bmi2: u1 = 0,
    /// Enhanced REP MOVSB/STOSB
    erms: u1 = 0,
    /// INVPCID Instruction
    invpcid: u1 = 0,
    /// Restricted Transactional Memory
    rtm: u1 = 0,
    /// Resource Director Technology Monitoring
    rdt_m: u1 = 0,
    /// Resource Director Technology Allocation
    rdt_a: u1 = 0,
    /// Memory Protection Extensions
    mpx: u1 = 0,
    /// Reserved (bit 15)
    _reserved_15: u1 = 0,
    /// Reserved (bits 16..31)
    _reserved_16_31: u16 = 0,
};

/// Leaf 7, Subleaf 0 ECX 中的特性标志（部分常用位）。
pub const Leaf7Sub0Ecx = packed struct(u32) {
    /// AVX-512 Foundation
    avx512f: u1 = 0,
    /// AVX-512 Doubleword and Quadword
    avx512dq: u1 = 0,
    /// AVX-512 ifma
    avx512ifma: u1 = 0,
    /// AVX-512 4-bit multiply accumulate
    avx512pf: u1 = 0,
    /// AVX-512 Exponential and Reciprocal
    avx512er: u1 = 0,
    /// AVX-512 Conflict Detection
    avx512cd: u1 = 0,
    /// AVX-512 Byte and Word
    avx512bw: u1 = 0,
    /// AVX-512 Vector Length Extensions
    avx512vl: u1 = 0,
    /// Reserved (bit 8..31)
    _reserved: u24 = 0,
};

/// Leaf 7, Subleaf 0 EDX 中的特性标志（部分常用位）。
pub const Leaf7Sub0Edx = packed struct(u32) {
    /// AVX-512 VPOPCNTDQ
    avx512vpopcntdq: u1 = 0,
    /// Reserved (bit 1)
    _reserved_1: u1 = 0,
    /// AVX-512 VNNI
    avx512vnni: u1 = 0,
    /// AVX-512 BITALG
    avx512bitalg: u1 = 0,
    /// AVX-512 VPCOMPRESS
    avx512vpcompress: u1 = 0,
    /// AVX-512 VBMI2
    avx512vbmi2: u1 = 0,
    /// Reserved (bits 6..31)
    _reserved: u26 = 0,
};

/// Leaf 7, Subleaf 0 完整信息。
pub const Leaf7Sub0 = struct {
    eax: u32, // 通常为 0
    ebx: Leaf7Sub0Ebx,
    ecx: Leaf7Sub0Ecx,
    edx: Leaf7Sub0Edx,
};

/// 返回 Leaf 7, Subleaf 0 信息。
pub fn getLeaf7Sub0() Leaf7Sub0 {
    const r = cpuid(7, 0);
    return .{
        .eax = r.eax,
        .ebx = @bitCast(r.ebx),
        .ecx = @bitCast(r.ecx),
        .edx = @bitCast(r.edx),
    };
}

// ----------------------------------------------------------------------
// 扩展 Leaf 0x80000001 – 扩展特性
// ----------------------------------------------------------------------
/// 扩展 Leaf 0x80000001 ECX 中的特性标志。
pub const ExtLeaf1Ecx = packed struct(u32) {
    /// LAHF/SAHF in 64-bit mode
    lahf_lm: u1 = 0,
    /// CMPXCHG16B (already in Leaf1, but repeated here)
    cmp_legacy: u1 = 0,
    /// SVM (Secure Virtual Machine)
    svm: u1 = 0,
    /// Extended APIC space
    ext_apic: u1 = 0,
    /// CR8 in 64-bit mode
    cr8_legacy: u1 = 0,
    /// Advanced Bit Manipulation
    abm: u1 = 0,
    /// SSE4A
    sse4a: u1 = 0,
    /// Misaligned SSE mode
    misalign_sse: u1 = 0,
    /// 3DNow! Prefetch
    prefetchw: u1 = 0,
    /// OS Visible Workaround
    osvw: u1 = 0,
    /// Instruction Based Sampling
    ibs: u1 = 0,
    /// XOP (eXtended Operations)
    xop: u1 = 0,
    /// SKINIT and STGI
    skinit: u1 = 0,
    /// Watchdog Timer
    wdt: u1 = 0,
    /// Reserved (bit 14..31)
    _reserved: u18 = 0,
};

/// 扩展 Leaf 0x80000001 EDX 中的特性标志。
pub const ExtLeaf1Edx = packed struct(u32) {
    /// x87 FPU On-Chip
    fpu: u1 = 0,
    /// Virtual 8086 Mode Extensions
    vme: u1 = 0,
    /// Debugging Extensions
    de: u1 = 0,
    /// Page Size Extension
    pse: u1 = 0,
    /// Time Stamp Counter
    tsc: u1 = 0,
    /// Model-Specific Registers
    msr: u1 = 0,
    /// Physical Address Extension
    pae: u1 = 0,
    /// Machine Check Exception
    mce: u1 = 0,
    /// CMPXCHG8B Instruction
    cx8: u1 = 0,
    /// APIC On-Chip
    apic: u1 = 0,
    /// Reserved (bit 10)
    _reserved_10: u1 = 0,
    /// SYSCALL/SYSRET
    syscall: u1 = 0,
    /// Memory Type Range Registers
    mtrr: u1 = 0,
    /// Page Global Enable
    pge: u1 = 0,
    /// Machine Check Architecture
    mca: u1 = 0,
    /// CMOV Instructions
    cmov: u1 = 0,
    /// Page Attribute Table
    pat: u1 = 0,
    /// 36-bit Page Size Extension
    pse36: u1 = 0,
    /// Reserved (bit 18)
    _reserved_18: u1 = 0,
    /// CLFLUSH Instruction
    clfsh: u1 = 0,
    /// Reserved (bit 20)
    _reserved_20: u1 = 0,
    /// Debug Store
    ds: u1 = 0,
    /// ACPI via MSR
    acpi: u1 = 0,
    /// MMX Technology
    mmx: u1 = 0,
    /// FXSAVE/FXRSTOR
    fxsr: u1 = 0,
    /// SSE Instructions
    sse: u1 = 0,
    /// SSE2 Instructions
    sse2: u1 = 0,
    /// Self Snoop
    ss: u1 = 0,
    /// 64-bit Mode (Long Mode)
    lm: u1 = 0,
    /// 3DNow! Extensions
    threednow_ext: u1 = 0,
    /// 3DNow! Instructions
    threednow: u1 = 0,
};

/// 扩展 Leaf 0x80000001 完整信息。
pub const ExtLeaf1 = struct {
    eax: u32, // 处理器签名（扩展）
    ebx: u32, // 保留/品牌
    ecx: ExtLeaf1Ecx,
    edx: ExtLeaf1Edx,
};

/// 返回扩展 Leaf 0x80000001 信息。
pub fn getExtLeaf1() ExtLeaf1 {
    const r = cpuid(0x80000001, 0);
    return .{
        .eax = r.eax,
        .ebx = r.ebx,
        .ecx = @bitCast(r.ecx),
        .edx = @bitCast(r.edx),
    };
}

// ----------------------------------------------------------------------
// 使用示例（可在测试中启用）
// ----------------------------------------------------------------------
test "cpuid leaf1" {
    const leaf1 = getLeaf1();
    std.debug.print("Leaf1: EAX=0x{X:0>8}, EBX=0x{X:0>8}\n", .{ leaf1.eax, leaf1.ebx });
    std.debug.print("  SSE3: {}\n", .{leaf1.ecx.sse3});
    std.debug.print("  AVX:  {}\n", .{leaf1.ecx.avx});
    std.debug.print("  SSE2: {}\n", .{leaf1.edx.sse2});
}

test "cpuid leaf7" {
    const leaf7 = getLeaf7Sub0();
    std.debug.print("Leaf7: EAX=0x{X:0>8}\n", .{leaf7.eax});
    std.debug.print("  AVX2: {}\n", .{leaf7.ebx.avx2});
    std.debug.print("  SMEP: {}\n", .{leaf7.ebx.smep});
}

test "cpuid ext leaf1" {
    const ext = getExtLeaf1();
    std.debug.print("ExtLeaf1: LM (long mode): {}\n", .{ext.edx.lm});
}
