// Debug framebuffer console.
// Generated by Deepseek V4.1 Flash
// NOTE: Independent from `drivers/framebuffer` so early/panic output always works.

const std = @import("std");

pub const glyph_width: u32 = 8;
pub const glyph_height: u32 = 16;

/// Printable ASCII range.
const font_first: u8 = 0x20;
const font_last: u8 = 0x7E;

/// 8x16 glyphs, top row first, MSB is the leftmost pixel.
const font = @embedFile("font8x16.bin");

// White on black, identical for RGB and BGR 32bpp.
const fg_color: u32 = 0x00FFFFFF;
const bg_color: u32 = 0x00000000;

const Console = struct {
    framebuffer: [*]u32,
    /// Pixels per scan line.
    pitch: u32,
    columns: u32,
    rows: u32,
    cursor_x: u32 = 0,
    cursor_y: u32 = 0,
};

var console: ?Console = null;

pub var writer: ?*std.Io.Writer = null;

const Writer = struct {
    interface: std.Io.Writer,

    fn drain(w: *std.Io.Writer, data: []const []const u8, splat: usize) std.Io.Writer.Error!usize {
        putBytes(w.buffer[0..w.end]);
        w.end = 0;

        var written: usize = 0;
        for (data[0 .. data.len - 1]) |bytes| {
            putBytes(bytes);
            written += bytes.len;
        }
        for (0..splat) |_| {
            const bytes = data[data.len - 1];
            putBytes(bytes);
            written += bytes.len;
        }
        return written;
    }

    const vtable: std.Io.Writer.VTable = .{ .drain = drain };
};

var fb_writer: Writer = .{
    .interface = .{
        .buffer = &.{},
        .vtable = &Writer.vtable,
    },
};

/// `base` is the mapped framebuffer address, `pitch` is pixels per scan line.
pub fn init(base: u64, width: u32, height: u32, pitch: u32) void {
    console = .{
        .framebuffer = @ptrFromInt(base),
        .pitch = pitch,
        .columns = width / glyph_width,
        .rows = height / glyph_height,
    };
    writer = &fb_writer.interface;
    @memset(console.?.framebuffer[0 .. pitch * height], bg_color);
}

/// Stop writing debug output to the framebuffer.
pub fn disable() void {
    writer = null;
}

fn putBytes(bytes: []const u8) void {
    for (bytes) |byte| putChar(byte);
}

fn putChar(byte: u8) void {
    const c = if (console) |*c| c else return;
    if (c.columns == 0 or c.rows == 0) return;

    switch (byte) {
        '\n' => newline(c),
        '\r' => c.cursor_x = 0,
        else => {
            if (byte < font_first or byte > font_last) return;
            drawGlyph(c, byte);
            advance(c);
        },
    }
}

fn drawGlyph(c: *Console, byte: u8) void {
    const base = @as(usize, byte - font_first) * glyph_height;
    const origin_x = c.cursor_x * glyph_width;
    const origin_y = c.cursor_y * glyph_height;

    var row: u32 = 0;
    while (row < glyph_height) : (row += 1) {
        const bits = font[base + row];
        const line = (origin_y + row) * c.pitch + origin_x;
        var col: u32 = 0;
        while (col < glyph_width) : (col += 1) {
            const mask: u8 = @as(u8, 0x80) >> @intCast(col);
            c.framebuffer[line + col] = if ((bits & mask) != 0) fg_color else bg_color;
        }
    }
}

fn advance(c: *Console) void {
    c.cursor_x += 1;
    if (c.cursor_x >= c.columns) {
        c.cursor_x = 0;
        newline(c);
    }
}

fn newline(c: *Console) void {
    c.cursor_x = 0;
    if (c.cursor_y + 1 < c.rows) {
        c.cursor_y += 1;
    } else {
        scroll(c);
    }
}

fn scroll(c: *Console) void {
    const row_pixels = c.pitch * glyph_height;
    if (c.rows > 1) {
        const copied = (c.rows - 1) * row_pixels;
        @memmove(
            c.framebuffer[0..copied],
            c.framebuffer[row_pixels .. row_pixels + copied],
        );
    }
    clearRow(c, c.rows - 1);
    c.cursor_y = c.rows - 1;
}

fn clearRow(c: *Console, row: u32) void {
    const row_pixels = c.pitch * glyph_height;
    const start = row * row_pixels;
    @memset(c.framebuffer[start .. start + row_pixels], bg_color);
}
